# The device(s) to use for recording (1) and playback (2). Each device is specified with an id (int) or (sub)string.
# Examples:
#     [1, 2]   -  1 is used for recording and 2 for playback
#     3        -  3 is used for recording and playback
#     Spark    -  search for a device that contains "Spark" in its name and use it for recording and playback
#     Null     -  use default devices
device: Null

# The latency of the audio stream. Higher values lead to more stable streams but decrease the snappiness
latency: 0.1
